name: Frontend Pipeline
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set GHCR_OWNER environment variable
              run: echo "GHCR_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

            - name: Login to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build with docker compose
              run: docker compose build

            - name: Push to GHCR
              run: docker compose push
    
    deploy:
        needs: build
        runs-on: ubuntu-latest

        env:
            DB_NAME: ${{ secrets.DB_NAME }}
            DB_USER: ${{ secrets.DB_USER }}
            DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            
        steps:
            - name: Set GHCR owner
              run: echo "GHCR_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

            - name: Checkout compose file
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                    docker-compose.yml
                    backend/init.sql
                sparse-checkout-cone-mode: false
                
            - name: Deploy to server
              run: |
                echo "${{ secrets.VM_SSH_KEY }}" > ssh_key
                chmod 600 ssh_key

                ssh -p "${{ secrets.VM_PORT }}" \
                -i ssh_key \
                ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
                "mkdir -p ~/url-shortener && cat > ~/url-shortener/.env <<EOF
                GHCR_OWNER=$GHCR_OWNER
                DB_NAME=$DB_NAME
                DB_USER=$DB_USER
                DB_PASSWORD=$DB_PASSWORD
                REDIS_HOST=$REDIS_HOST
                REDIS_PORT=$REDIS_PORT
                EOF"

                scp -P "${{ secrets.VM_PORT }}" \
                -i ssh_key docker-compose.yml \
                ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/url-shortener/docker-compose.yml

                ssh -p "${{ secrets.VM_PORT }}" \
                -i ssh_key \
                ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
                "cd ~/url-shortener && docker compose pull && docker compose up -d"

            